version: "1.0"
info:
  scaffold: GetDate4Shashi
  model: int-scaffold
services:
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.286
- serviceName: edge.owngit4host.integrations:GetDate4Shashi
  packages:
  - name: EdgeOwnGIT4HOST
    version: "1.0"
- serviceName: pub.date:getCurrentDateString
  packages:
  - name: WmPublic
    version: 11.0.0.0.286
