version: "1.0"
info:
  scaffold: GetMoreDates4Dave
  model: int-scaffold
services:
- serviceName: edge.owngit4host.integrations:GetMoreDates4Dave
  packages:
  - name: EdgeOwnGIT4HOST
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.286
- serviceName: pub.date:getCurrentDateString
  packages:
  - name: WmPublic
    version: 11.0.0.0.286
