version: "1.0"
info:
  scaffold: GetMoreDates
  model: int-scaffold
services:
- serviceName: edge.owngit4host.integrations:GetMoreDates
  packages:
  - name: EdgeOwnGIT4HOST
    version: "1.0"
- serviceName: pub.date:getCurrentDateString
  packages:
  - name: WmPublic
    version: 11.0.0.0.286
